### ISSUE TITLE
UnicodeDecodeError when 3 rigid bodies are in view of the Polaris Vicra

### ISSUE THREAD

**Issue by Larbino1** [PlusToolkit/ndicapi#46]
Stracktrace:
```
Traceback (most recent call last):
  File "/home/daniellarby/camtracking/vicra/VicraJuliaClient.py", line 142, in <module>
    vc.run()
  File "/home/daniellarby/camtracking/vicra/VicraJuliaClient.py", line 49, in run
    port_numbers, timestamps, framenumbers, transforms, quality = self.tracker.get_frame()
  File "/home/daniellarby/.local/lib/python3.8/site-packages/sksurgerynditracker/nditracker.py", line 461, in get_frame
    ndicapy.ndiCommand(self._device, self._capture_string)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 2: invalid start byte
```
This reliably happens when I move a third rigid body into the view of the Polaris vicra. Otherwise, tracking works perfectly.

I would really appreciate a bit of guidance as to where to look to fix this problem. Am I right that the error is in this repository, ndicapi? Where does ndicapy reside? Is the Error thrown from python or C++ code?

**Comment by Larbino1** [comment]
@thompson318

**Comment by thompson318** [comment]
This may be a problem with trying to use BX transforms. Have a look at [_set_use_bx_transforms](https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/6776a367942592602c12e29b7eb3826890c760e9/sksurgerynditracker/nditracker.py#L157) in nditracker.py. You can add your devices firmware string to the list at [line 169](https://github.com/SciKit-Surgery/scikit-surgerynditracker/blob/6776a367942592602c12e29b7eb3826890c760e9/sksurgerynditracker/nditracker.py#L169). If that fixes your problem then you should probably transfer this issue to scikit-surgeryndirtracker and create a pull request there.

**Comment by thompson318** [comment]
We've seen very similar with other trackers: see https://github.com/SciKit-Surgery/scikit-surgerynditracker/issues/17

**Comment by lassoan** [comment]
A binary buffer is attempted to be interpreted as utf8 encoded string, but of course not all binary stream is valid utf8. To fix it, replace `PyString_AsString` in `ndicapy.ndiCommand` to return a bytes object instead (or maybe a latin1-encoded string would work, too).

**Comment by Larbino1** [comment]
> A binary buffer is attempted to be interpreted as utf8 encoded string, but of course not all binary stream is valid utf8. To fix it, replace `PyString_AsString` in `ndicapy.ndiCommand` to return a bytes object instead (or maybe a latin1-encoded string would work, too).

Thanks for the help - I suspected it would be something like this but couldn't find where it was happening. With your comment I've found where this is in the code, built the code and started trying to make a fix! 

I'm looking at using PyBytes_FromString instead of PyUnicode_FromUTF8 where a command is received, but this change results in other errors, which I'm now hunting down.
